---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - env:
        - name: MY_ENV_VAR
          valueFrom:
            secretKeyRef:
              key: my-env-var
              name: my-secret
        image: ghcr.io/saroj-nayak/dev-kube:main
        name: my-app
        ports:
        - containerPort: 80
      secrets:
      - name: my-secret
        secret:
          items:
          - key: my-env-var
            path: env.txt
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
spec:
  rules:
  - host: my-app.example.com
    http:
      paths:
      - backend:
          service:
            name: my-app-service
            port:
              name: http
        path: /
        pathType: Prefix
---
apiVersion: v1
data:
  my-env-var: Z2hwX2I1WFJEb1dnTjlBOTZvcURKeWY3Rkl3aXhyb0toYjNYMjFIYQo=
kind: Secret
metadata:
  name: my-secret
type: Opaque

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: NodePort
