name: Build and Push to GH Container Registry

on: push

jobs:
 build:
 runs-on: ubuntu-latest
 steps:
  - uses: actions/checkout@v2
  - name: Build Docker Image
    run: |
     docker build -t ghcr.io/saroj-nayak/html-server-image:latest .
  - name: Login to GHCR 
   - uses: docker/login-action@v1  
     with: 
     registry: ghcr.io 
     username: ${{ secrets.GHCR_USERNAME }} 
     password: ${{ secrets.GHCR_TOKEN }}
           
  - name: Push Docker Image
    run: |
     docker push ghcr.io/saroj-nayak/html-server-image:latest   
