name: Build and Push to GH Container Registry

on: push

jobs:
         build:
          runs-on: ubuntu-latest
          steps:
           - uses: actions/checkout@v2
           - name: Build Docker Image
             run: |
              docker build . --tag ghcr.io/Saroj-Nayak/html-server-image:latest
           - name: Docker Login
             run: |
              echo ${{ secrets.ACCESSSECRET }} | docker login ghcr.io -u "Saroj-Nayak" --password-stdin
           - name: Push Docker Image
             run: |
              docker push ghcr.io/Saroj-Nayak/html-server-image:latest   
