name: Build and Push to GH Container Registry

on: push

jobs:
 build:
  runs-on: ubuntu-latest
 
  steps:
  - uses: actions/checkout@v1
  - name: Build Docker Image
    run: |
    docker build -t ghcr.io/saroj-nayak/html-server-image:latest .
    
  - name: Docker Login
    run: |
    docker login ghcr.io -u $ghcr_user -p $secrets.ACCESSSECRET
     
  - name: Push Docker Image
    run: |
    docker push ghcr.io/saroj-nayak/html-server-image:latest   
          
