name: Publish to GH Container Registry

on: push

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - name: Build Docker Image
     run: |
      docker build -t html-server-image:latest .
   - name: Docker Login
     run: |
      echo ${{ secrets.ACCESSSECRET }} | docker login ghcr.io -u ${{ secrets.REGISTRY_USR }} --password-stdin
   - name: Push Docker Image
     run: |
      docker push ghcr.io/Saroj-Nayak/html-server-image:latest       
